version: '2.1'

volumes:
    adguardhome:
    letsencrypt:

services:

    # https://hub.docker.com/r/adguard/adguardhome
    adguard:
        image: adguard/adguardhome:arm64-v0.100.8
        network_mode: host
        privileged: true
        volumes:
            - 'adguardhome:/opt/adguardhome:rw'
            - 'letsencrypt:/etc/letsencrypt:ro'

    certbot:
        build: ./certbot
        volumes:
            - 'letsencrypt:/etc/letsencrypt:rw'
        ports:
            - '80:80/tcp'
