version: '2.1'

volumes:
    adguardhome_work:
    adguardhome_conf:
    letsencrypt:

services:

    adguard:
        build: ./adguard
        network_mode: host
        privileged: true
        volumes:
            - 'adguardhome_work:/opt/adguardhome/work:rw'
            - 'adguardhome_conf:/opt/adguardhome/conf:rw'
            - 'letsencrypt:/etc/letsencrypt:ro'

    certbot:
        build: ./certbot
        volumes:
            - 'letsencrypt:/etc/letsencrypt:rw'
        ports:
            - '80:80/tcp'
