version: '2.1'

volumes:
  work:
  conf:

services:
  adguard:
    image: adguard/adguardhome:arm64-latest
    network_mode: host
    privileged: true
    volumes:
      - 'work:/opt/adguardhome/work'
      - 'conf:/opt/adguardhome/conf'
