version: '2.1'

volumes:
  work:
  conf:
  letsencrypt:

services:
  adguard:
    # https://github.com/AdguardTeam/AdGuardHome/wiki/Docker
    # https://hub.docker.com/r/adguard/adguardhome
    image: adguard/adguardhome:arm64-v0.97.1
    network_mode: host
    privileged: true
    volumes:
      - 'work:/opt/adguardhome/work'
      - 'conf:/opt/adguardhome/conf'
  
  dns-cloudflare:
    # https://github.com/AdguardTeam/AdGuardHome/wiki/Encryption
    build: ./dns-cloudflare
    volumes:
      - 'letsencrypt:/etc/letsencrypt'
