version: '2.1'

volumes:
    adguardhome:
    letsencrypt:

services:

    # https://hub.docker.com/r/adguard/adguardhome
    adguard:
        image: adguard/adguardhome:arm64-v0.99.0
        network_mode: host
        privileged: true
        volumes:
            - 'adguardhome:/opt/adguardhome:rw'
            - 'letsencrypt:/etc/letsencrypt:ro'
        command: --port 80

    certbot:
        build: ./certbot
        volumes:
            - 'letsencrypt:/etc/letsencrypt:rw'
